### ISSUE TITLE
Viewer KO with Firefox v111.0.1 (Win10 x64)

### ISSUE THREAD

**Issue by yvanblanchard** [gkjohnson/closed-chain-ik-js#109]
There is no model display in FireFox browser (Ok with my Chrome browser)

![image](https://user-images.githubusercontent.com/63931618/229355097-0b4ff6d9-45fa-45da-94fe-c48172d783c7.png)

**Comment by gkjohnson** [comment]
I'm not able to repro this - can you provide more error logs.
